version: '3'
services:
  proxy:
    build: proxy
    container_name: proxy
    hostname: proxy
    ports:
      - 8081:80
    restart: always
  backend1:
    build: backend1
    container_name: backend1
    hostname: backend1
    command: python3 main.py
    ports:
      - 5001:5001
    restart: always
  backend2:
    build: backend2
    container_name: backend2
    hostname: backend2
    command: python3 main.py
    ports:
      - 5002:5002
    restart: always
  backend3:
    build: backend3
    container_name: backend3
    hostname: backend3
    command: python3 main.py
    ports:
      - 5003:5003
    restart: always
